name: CD

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
    - run: |
        git config user.name JakeAdler
        git config user.email 39200701+JakeAdler@users.noreply.github.com
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Bump version and generate changelog
      run: npx standard-version --prerelease
    - name: Commit version change and changelog
      ## TODO: Change this commit message
      run: git add . && git commit -m "From github action"
    - name: Push git tags
      run: git push --follow-tags origin master
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist/ 

  publish_npm: 
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        registry-url: 'https://registry.npmjs.org'
        scope: 'algotia'
    - name: Download build artifacts
      uses: actions/download-artifact@v1
      with:
        name: dist
    - name: Publish to NPM
      run: npm publish
      env: 
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  
  publish_gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        registry-url: 'https://npm.pkg.github.com/'
        scope: '@algotia'
    - name: Download build artifacts
      uses: actions/download-artifact@v1
      with:
        name: dist
    - name: Publish to GPR
      run: npm publish
      env: 
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
