name: CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with: 
        persist-credentials: false
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Semantic release
      env: 
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release --prerelease


# 
  #publish_npm: 
    #needs: build
    #runs-on: ubuntu-latest
    #steps:
    #- uses: actions/checkout@v2
    #- name: Setup Node.js environment
      #uses: actions/setup-node@v1.4.2
      #with:
        #registry-url: 'https://registry.npmjs.org'
        #scope: 'algotia'
    #- name: Download build artifacts
      #uses: actions/download-artifact@v1
      #with:
        #name: dist
    #- name: Publish to NPM
      #run: npm publish
      #env: 
        #NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  
  #publish_gpr:
    #needs: build
    #runs-on: ubuntu-latest
    #steps:
    #- uses: actions/checkout@v2
    #- name: Setup Node.js environment
      #uses: actions/setup-node@v1.4.2
      #with:
        #registry-url: 'https://npm.pkg.github.com/'
        #scope: '@algotia'
    #- name: Download build artifacts
      #uses: actions/download-artifact@v1
      #with:
        #name: dist
    #- name: Publish to GPR
      #run: npm publish
      #env: 
        #NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
